#!/bin/sh

# This script contains the specific part for CI on IBM power computer (ppc64le)

#start debugging
set -x


wget http://www.silx.org/pub/ppc64le/HDF5-1.10.5-ppc64le.tar.gz
tar -xvzf HDF5-1.10.5-ppc64le.tar.gz
export HDF_PATH=${PWD}/HDF5-1.10.5
